-- Transaction fact, 1 row per decision emitted (spec 05 §8) — same grain as
-- the source, literally the audit trail price_decision.v1 itself promises
-- ("reconstruct exactly why a price was set, months later").
select
    decision_id,
    apartment_id,
    target_date,
    decided_at,
    total_monthly_cost_eur,
    fixed_cost_eur,
    variable_cost_eur,
    per_booking_cost_eur,
    fixed_and_allocated_costs_eur,
    p,
    cost_lines_count,
    cost_breakdown,
    avg_nightly_rate_eur,
    occupancy_rate,
    sample_size,
    market_collected_at,
    data_age_seconds,
    target_margin,
    minimum_price_eur,
    break_even_revenue_eur,
    profitable_floor_eur,
    floor_policy,
    commission_pct,
    commission_base,
    days_to_arrival,
    competitiveness_discount,
    property_attribute_factor,
    property_reference_price_eur,
    market_reference_price_eur,
    rule_applied,
    los_floor_matrix,
    decision_components,
    manual_override,
    minimum_stay_recommendation,
    channel_price_matrix,
    suggested_price_eur,
    currency,
    effective_margin,
    below_market_by,

    -- used by the dashboard's freshness indicator
    dynamodb_event_name,
    ingested_at
from {{ ref('stg_price_decision') }}
